docs/resources/corp_rule.md
docs/resources/site_rule.md

Both the "enabled" and "expiration" parameters are required but not currently noted as such.

Clarify required parameters for corp/site rules

---

docs/resources/site_rule.md

`rateLimit` already works and is a valid option in the [codebase](https://github.com/signalsciences/terraform-provider-sigsci/blob/ca52359600535d027a8675b0def5896d2668cf99/provider/resource_site_rule.go#L20) but not in the documentation. 
Therefore, in order to make it clearer for consumers of this provider, it is a good idea to include the valid option in the documentation.

DOCUMENTATION: Update the 'type' options to include 'rateLimit' in site rules

---

provider/resource_site.go

A user does not want sensitive secret information to be stored in their logs.
Internal Slack conversation: https://fastly-support.slack.com/archives/C03KSJGM9CJ/p1659455064094449

Redact access_key/secret_key secrets from stdout

---

docs/resources/site_alert.md

[Issue-64](https://github.com/signalsciences/terraform-provider-sigsci/issues/64)
In the [documentation](https://registry.terraform.io/providers/signalsciences/sigsci/latest/docs/resources/site_alert), interval and threshold are not marked as required fields but while applying the change in terraform, you get the followig errors: 
* `Error: Interval must be 1, 10 or 60`. 
* `Error: Threshold must be between 1 and 10000`
This change marks them as a required field.

[Issue-64] Mark interval as required field for site alerts

---

README.md

Hi, 
A change was omitted in the README.md and has been corrected.
ref. https://github.com/signalsciences/terraform-provider-sigsci/releases/tag/v0.4.4

FIX: Readme

---

provider/resource_corp_cloudwaf_instance.go
provider/resource_corp_cloudwaf_instance_test.go

Enhancement to add Cloud WAF Instance read response computed properties for:
1. ~~`cloudwaf_instance_id` - This maps to the API response `id` property. The name has been modified for Terraform as `id` is not an allowed field name. The error is `id is a reserved field name for a resource`. See more here: https://github.com/russellcardullo/terraform-provider-pingdom/issues/11~~ removed as duplicate to `id` value.
2. `deployment` - This maps to the `deployment` API response property. While this is a JSON object in the API response, this is currently implemented as  `schema.TypeList` with `MaxItems` set to `1` instead of being a `schema.TypeMap` due to a limitation in the Terraform Provider Go SDK which requires `schema.TypeMap` values to be strings. Using a `TypeList` wil result in …

Add Cloud WAF Instance response computed properties

---

.github/workflows/build.yml

A PR like [this one](https://github.com/signalsciences/terraform-provider-sigsci/pull/81) should fail because it uses an attribute (`BlockDurationSeconds`) which doesn't exist yet in the `go-sigsci` library. 
A call to `go build` would fail in that case:
```
➜  terraform-provider-sigsci git:(alert-blockduration) go build ./...
provider/resource_site_alert.go:78:3: unknown field 'BlockDurationSeconds' in struct literal of type sigsci.CustomAlertBody
provider/resource_site_alert.go:150:3: unknown field 'BlockDurationSeconds' in struct literal of type sigsci.CustomAlertBody
```

add go build github workflow

---

provider/resource_site_rule.go

Hi, 
Fixed a bug in `sigsci_site_rule` of terraform-provider-sigsci v1.2.0 released yesterday, which caused errors such as `terarform plan`.
related issue: https://github.com/signalsciences/terraform-provider-sigsci/issues/89

[BUG] Fixed resource schema for `requestlogging` in `sigsci_site_rule`

---

provider/resource_site_rule.go
provider/resource_site_rule_test.go

`requestlogging` is not modifiable on rate limit rules, so it can be confusing when running `terraform plan` shows `requestlogging` in the diff for a rate limit rule like shown in https://github.com/signalsciences/terraform-provider-sigsci/issues/68#issuecomment-1375710968.

remove requestlogging default from site rule resource

---

provider/resource_site_integration.go

Related: https://github.com/signalsciences/terraform-provider-sigsci/issues/50
This surfaces the actual error when an update fails, so we don't need to run with `TF_LOG=1` to see it.

return error when updating an integration fails

---

provider/resource_site.go

Terraform Destroy currently reveals sensitive values as a result of the issue described with nested element in:
https://github.com/hashicorp/terraform-plugin-sdk/issues/736
Output:
```
❯ terraform destroy
sigsci_site.terraform_site: Refreshing state... [id=terraform_site]
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
- destroy
Terraform will perform the following actions:
- resource "sigsci_site" "terraform_site" {
- agent_level            = "block" -> null
- block_duration_seconds = 86400 -> null
- block_http_code        = 406 -> null
- display_name           = "jeremys terraform site" -> null
- id                     = "terraform_site" -> null
- primary_agent_key      = {
- "access_key" = …
```

Set sensitive value at atttribute level to fix terraform destroy exposing sensitive values

---

provider/resource_site_rule_test.go

Fixes Error: Tag with that name exists when running the two tests at the same time.

use different tag name in TestACCResourceSiteRuleRateLimit_basic to avoid race condition with TestAccResourceSiteSignalTagCRUD

---

docs/resources/site_alert.md
docs/resources/site_rule.md
provider/resource_site_alert.go

When interval, threshold, or action are not set on site alert we get the following errors:
```
│ Error: Interval must be 1, 10 or 60
│ 
│   with sigsci_site_alert.test,
│   on main.tf line 23, in resource "sigsci_site_alert" "test":
│   23: resource "sigsci_site_alert" "test" {
```
```
│ Error: Threshold must be between 1 and 10000
│ 
│   with sigsci_site_alert.test,
│   on main.tf line 23, in resource "sigsci_site_alert" "test":
│   23: resource "sigsci_site_alert" "test" {
```
```
│ Error: Action must be 'flagged' or 'info'
│ 
│   with sigsci_site_alert.test,
│   on main.tf line 23, in resource "sigsci_site_alert" "test":
│   23: resource "sigsci_site_alert" "test" {
```
- set interval and threshold as required on site alert
- generate docs
Related: …

site alert interval, threshold, action required

---

docs/index.md
provider/provider.go
templates/index.md.tmpl

This adds a `validate` provider option that can be set to `false` when you need to skip validation of API credentials.
Fixes #71

Add validate option to allow bypassing of API credential check

---

examples/resources/sigsci_site_rule/resource.tf

We recently released an update to the rate limit rules user experience. While this change did not impact the API it did introduce a new signal `ALL-REQUESTS` that can be used when configuring rate limit rules. It has also been requested that we expand the terraform examples to show how different configurations that are done through the UI could be done within terraform.
This commit adds all 3 examples that could be configured from within the UI.
The example does not include the corresponding signal creation as the existing rule also did not include that.

MINOR: examples: expand rate limit rule examples

---

provider/resource_corp_rule_test.go

This test frequently fails because one of the sites it tries to create already exists from a previous test. Removing `t.Parallel()` seems to fix this.

remove t.Parallel() in TestResourceCorpRule_SortedSiteNames

---

provider/lib.go
provider/resource_corp_cloudwaf_instance.go
provider/resource_site.go

Hi, I added some validateFunc to `sigsci_corp_cloudwaf_instance` resource.
- `region`
- Whether is in region list. ([doc](https://docs.fastly.com/signalsciences/api/#_corps__corpName__cloudwafInstances_post))
- `instance_location`
- "direct" or "advanced"
- `workspace_configs.routes.domains`
- Whether less than equal 100 entries
region
```console
$ terraform validate
│ Error: received region name 'ap-northeast-10' is invalid. should be in (us-east-1, us-west-1, af-south-1, ap-northeast-1, ap-northeast-2, ap-south-1, ap-southeast-1, ap-southeast-2, ca-central-1, eu-central-1, eu-north-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-2, us-west-2)
│
│   with sigsci_corp_cloudwaf_instance.name,
│   on cloudwaf.tf line 1, in resource "sigsci_corp_cloudwaf_instance" "name":
│    1: …
```

change: added ValidateFunc for `sigsci_corp_cloudwaf_instance`

---

provider/resource_corp_integration.go

Hi, I added a validateFunc to `sigsci_corp_integration` resource.
- type
- "mailingList", "slack" or "microsoftTeams"
```console
$ terraform validate
│ Error: received type 'Slack' is invalid. should be 'mailingList', 'slack', or 'microsoftTeams'
│
│   with module.corp.sigsci_corp_integration.name,
│   on corp/integration.tf line 1, in resource "sigsci_corp_integration" "name":
│    1: resource "sigsci_corp_integration" "name" {
```

change: added ValidateFunc for `sigsci_corp_integration`

---

provider/lib.go
provider/resource_corp_integration.go
provider/resource_corp_list.go

Hi, 
Added some ValidateFunc for `sigsci_corp_list`. 
- `name`
- `type`
- `description`
Also, added new function “validStringLength” in `lib.go`. It’s validate of string length. It's useful when you need to validate the string length.
Since the WebUI displays validation rules when an invalid value is entered, I considered creating a function like "validRegex" that could validate these using regular expressions.
(For example: https://github.com/hashicorp/terraform-provider-aws/blob/3db3102b34357187208b87b6825b6dcfd65e4bbb/.ci/providerlint/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation/strings.go#L90-L106)
However, since the official documentation does not mention validation using regular expressions, I limited ourselves to length validation. …

Added ValidateFunc for `sigsci_corp_list`

---

docs/resources/site.md
docs/resources/site_rule.md
go.mod
go.sum
provider/lib.go
provider/resource_site.go
provider/resource_site_rule.go

This commit allows updating the default WAF blocking code. It supports blocking using 301 or 302 with a custom URL as well as 400-599. It also extends support for the existing site rule blocking codes to allow for the same response codes.
This commit requires the merge of signalsciences/go-sigsci#53

MEDIUM: site: allow updating default WAF block code

---

provider/resource_site.go

It was pointed out in #161 that since the release of version 1.2.21 changes to apply continuously appear even when none are made if `block_http_code` was not specified. @sjparkinson rightfully pointed out the culprit was 2f7a101 (MEDIUM: site: allow updating default WAF block code)
Specifically, what was happening is that the API always responds with `blockHTTPCode` set even when it's using the default "406". However, from the terraform perspective this value was set to "null" and so it assumed that the 406 needed to be switched to "null". This commit updates the site resource file and properly sets "406" as the default. This fixes the conflict that was happening.

BUG/MINOR: site: set default block_http_code

---

docs/resources/site_rule.md
provider/resource_site_rule.go

The [API docs](https://docs.fastly.com/signalsciences/api/#_corps__corpName__sites__siteName__rules_post) list `matches` & `doesNotMatch` as available options for the POST Create Site Rule. I've tested creating a rule with terraform that uses both operators, and it works fine.
Just adding the corrected operator list to the docs.

update site_rule doc with missing operator options

---

provider/lib.go
provider/lib_test.go
provider/resource_corp_rule.go
provider/resource_site_rule.go

This PR adds `responseHeader` to the valid condition fields. According to Fastly support and the SigSci dashboard, response headers are a valid attribute to set conditions against. The TF provider does not currently agree and the spurious warnings make it hard to debug other SigSci issues. This adds `responseHeader` to the list to prevent these warnings.
The description in the resource schemas also pull the fields from a variable now  to avoid having to keep the actual validation and the documentation in sync in six places.
----
Thank you!

Add responseHeader to valid condition fields

---

docs/resources/corp_integration.md
docs/resources/corp_rule.md
docs/resources/site_integration.md
docs/resources/site_rule.md
provider/lib.go
provider/resource_corp_integration.go
provider/resource_corp_rule.go
provider/resource_site_integration.go
provider/resource_site_rule.go

This commit updates the documenation with the following changes:
* Replaces docs.signalsciences.net with proper docs.fastly.com URLs
* Splits `field` types into "single" and "multival" with the valid values for each
* Expands requestlogging to indicate that it is only valid for rules of type "request" and explicitly calls out that it is not valid for "signal" or "rateLimit"
* Fixes "signal exclusion" to be "signal"
* Fixes corp rule types to have addSignal, excludeSignal

DOC: update multival usage and add docs.fastly.com links

---

provider/lib.go
provider/resource_corp_rule.go
provider/resource_site_rule.go

requestLogging is an optional parameter that can be specified within request rules. It defaults to "sampled", however, if you create a rule without specifying it, it can cause terraform to mark a change as happening even though one was not expected. e.g.
```
+ requestlogging  = "sampled"
```
In other situations, we could just set the default in the provider to be "sampled". However, because requestLogging is not valid with all rule types and at the time of this commit terraform does not allow you to do pre-validation on multiple fields.
For this reason, we need to use `DiffSuppressFunc` to ignore the diff if `requestLogging` was not specified but the API responded with `sampled`.

BUG/MINOR: rules: suppress requestLogging default

---

docs/resources/edge_deployment.md
examples/resources/sigsci_edge_deployment/resource.tf

looks like the resource missing a `name` in the docs. cc @daniel-corbett

docs: fix `sigsci_edge_deployment` resource

---

provider/lib.go

In e293b90 (BUG/MINOR: rules: suppress requestLogging default), an attempt to suppress the diff creation when requestlogging was not specified (e.g. default) was made. However, it seems that the patch confused "new" and "old" values. This commit properly swaps the order and produces the expected results.

BUG/MINOR: rules: suppress requestLogging default (again)

---

main.tf

Some of the examples in main.tf were not valid. (e.g. using requestLogging in signal exclusion). This commit updates the examples to be valid, which should prevent some of the unnecessary diffs from continuing to show up when changes have not been made.

BUG/MINOR: main: update with valid examples

---

README.md
docs/index.md
templates/index.md.tmpl

since the project is already go modules based, there is no need to have references for GOPATH

docs: remove gopath and specify min go version constraint

---

provider/lib.go

In 4006a6c (BUG/MINOR: do not set default response code) the default to 406 was removed from rules without response codes. However, the provider was still forcing a 406 default behind the scenes causing rules without response codes to be recreated with 406 with every new plan apply.
This commit stops forcing the HTTP status code 406 on rules and fixes the issue with rules that have not had changes happen from being recreated.

BUG/MINOR: lib: don't force response code to 406

---

README.md
docs/index.md
examples/provider/provider.tf
main.tf
provider/config.go
provider/provider.go
templates/index.md.tmpl

Hi, 
I renamed `FASTLY_KEY` to `FASTLY_API_KEY`. Because it's useful when using [terraform-provider-fastly](https://github.com/fastly/terraform-provider-fastly) and [terraform-provider-sigsci](https://github.com/signalsciences/terraform-provider-sigsci) in same project. For example, you can unitifaction credentials set in CI/CD.
ref. 
- terraform-provider-fastly
- https://github.com/fastly/terraform-provider-fastly/blob/0927a692f90c6614fa8fc87aacdc60704a70a403/fastly/provider.go#L21-L26
- Isssue
- https://github.com/signalsciences/terraform-provider-sigsci/issues/188

change: `FASTLY_KEY` rename to `FASTLY_API_KEY`

---

provider/lib.go

It was reported that when using `redirect_url` changes were being presented when applying a plan, even though there were not any changes being made.
This was due to `redirect_url` not being reset during rule flattening within `flattenRuleActions`.
This commit fixes that and adds `redirect_url` to the `actionmap` within `flattenRuleActions`.

BUG/MEDIUM: rules: add redirect_url when flattening

---

docs/resources/site_rule.md
go.mod
go.sum
provider/lib.go
provider/resource_site_rule.go

This commit adds support for the `browserChallenge` action type within a Site Rule. Specifically, it documents that `browserChallenge` is available with action types. It also adds support for the `allowInteractive` boolean, which allows for toggling between non-interactive and interactive challenges.
This commit depends on signalsciences/go-sigsci#60

MINOR: site_rule: add support for browserChallenge

---

docs/resources/site_rule.md
provider/resource_site_rule.go

This commit extends the documentation to make it clear that `verifyToken` is usable as an action within a site rule.

DOC: add verifyToken to site rules

---

provider/lib.go
provider/provider.go
provider/resource_edge_deployment_service_update_backend.go

Fixes #201 
When multiple calls to `edgeDeployment/<sid>/backends` occur simultaneously for different service IDs during a single Terraform apply, it's common for one to fail with the error message: `Error: failed to activate service.` This issue seems to stem from an API constraint.
This PR introduces a provider mutex that can be used to serialize access to this API call (and could also be used for others, if required). This avoids the need to set `-parallelism=1` globally, which we'd prefer not to do when running alongside the `fastly` provider, because it would unnecessarily limit the throughput of that provider as well.

Serialize edge deployment backend updates via mutex

---

docs/resources/site_rule.md
provider/resource_site_rule.go

This commit updates the documentation for rate limit rules to specify that browserChallenge and verifyToken are now usable.

DOC: rules: add browserChallenge to rate limit rule

---

provider/resource_edge_deployment.go
provider/resource_edge_deployment_service.go

It was recently reported by @sloh-fastly that if a `sigsci_edge_deployment` was created without a `sigsci_site` it appeared to have been created within Terraform state. This caused some weird inconsistencies and could lead to the below error:
```
Error: Provider produced inconsistent result after apply
When applying changes to sigsci_site.acme_nginx_waf["stg"], provider
"provider[\"registry.terraform.io/signalsciences/sigsci\"]" produced an
unexpected new value: Root resource was present, but now absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Shu provided a thorough outline to reproduce, unfortunately I was not able to reproduce. However, I was able to identify what I believe to be happening. It seemed that even though the …

BUG/MEDIUM: edge: avoid setting state until success

---

go.sum
provider/lib.go
provider/resource_site.go

Hi, added error check to some functions.

chore: added error check to some functions

---

.github/workflows/release.yml

goreleaser has deprecated (and removed) --rm-dist. They are suggesting migration to `--clean`.
https://goreleaser.com/deprecations/#scoop

BUG/MINOR: release: remove deprecated --rm-dist

---

docs/resources/edge_deployment_service.md
docs/resources/site_agent_alert.md
go.mod
go.sum
provider/resource_edge_deployment_service.go

This commit adds the new option `custom_client_ip` to the Edge deployment resource. This option prevents the Fastly-Client-IP header from being overwritten by the NGWAF. It is intended for advanced use cases.

MINOR: edge: add new custom_client_ip option

---

docs/resources/corp_signal_tag.md
docs/resources/site_signal_tag.md
provider/resource_corp_signal_tag.go
provider/resource_corp_signal_tag_test.go
provider/resource_site.go
provider/resource_site_signal_tag.go
provider/resource_site_signal_tag_test.go
provider/resource_site_test.go

After getting burnt on a few apply-time errors in a gitops environment, I was hoping to add a few validation checks.
https://github.com/signalsciences/terraform-provider-sigsci/issues/233

add some unit test validations

---

docs/resources/corp_integration.md
docs/resources/site_integration.md
provider/resource_corp_integration.go
provider/resource_site_integration.go

This commit adds support for "Microsoft Teams (Workflows)". The integration type can be invoked through `microsoftTeamsWorkflow`.

MINOR: integrations: add support for microsoftTeamsWorkflow

---

go.mod
go.sum

This commit bumps the version of go-sigsci to v0.1.30.
Specifically it brings in the following change:
* BUG/MEDIUM: api: exclude DELETE calls from content-type check signalsciences/go-sigsci#74

MINOR: bump go-sigsci to v0.1.30

---

provider/resource_edge_deployment_service.go

It was recently identified by @BrooksCunningham that updating the `site_short_name` on a `sigsci_edge_deployment_service` object resulted in an error (`failed to attach service`). Successive runs of `terraform apply` would result in a succes, however, ultimately it was not working as expected.
This update of the `site_short_name` is what is known and documented as a "re-map" [1]. As the documentation shows, it requires first detaching the old workspace from the service using a `DELETE` call and then attaching a new workspace with a `PUT` call.
Previously, both Create & Update were using the same function, which prohibited proper detachment.
This commit introduces a update specific function `updateEdgeDeploymentService` and renames the existing `createOrUpdateEdgeDeploymentService` …

BUG/MEDIUM: edge: fix remapping of service to another workspace

---

docs/resources/site_integration.md

...as the customer didn't know how to specify the API key and the region/site.

Provide an example for Datadog's integration
